markdown:           redcarpet
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

permalink:           pretty

# Setup
title:               Roman Tsegelskyi's blog
tagline:             ''
description:         Roman Tsegelskyi's blog about different things related to software engineering
home:                http://romantsegelskyi.github.io
url:                 http://romantsegelskyi.github.io/blog
baseurl:             /blog
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# About/contact
author:
name:              Roman Tsegelskyi
url:               http://romantsegelskyi.github.io
email:             romantsegelskyi@gmail.com

# Custom vars
version:             1.0.0

## This is the list of pages to include in the header of the website.
pages_list:       
  About: '/blog/about'
  Atom: '/blog/atom.xml'
  RSS: '/blog/rss.xml'

gems: [jekyll-paginate]
