# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#
#

markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Programming Inverstigations
tagline:             ''
description:         ''
home:                http://romantsegelskyi.github.io
url:                 http://romantsegelskyi.github.io/pi-blog
baseurl:             /pi-blog
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# About/contact
author:
name:              Roman Tsegelskyi
url:               http://romantsegelskyi.github.io
email:             romantsegelskyi@gmail.com

# Custom vars
version:             1.0.0
