markdown:            kramdown

permalink:           pretty

# Setup
title:               Programming Inverstigations
tagline:             ''
description:         ''
home:                http://romantsegelskyi.github.io
url:                 http://romantsegelskyi.github.io/pi-blog
baseurl:             /pi-blog
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# About/contact
author:
name:              Roman Tsegelskyi
url:               http://romantsegelskyi.github.io
email:             romantsegelskyi@gmail.com

# Custom vars
version:             1.0.0

## This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about'
  Feed: '/atom.xml' 

